language: python
python:
  - "3.4.2"
  - "3.4.4"
env:
  - CIRCLE_NODE_TOTAL=8 CIRCLE_NODE_INDEX=0
  - CIRCLE_NODE_TOTAL=8 CIRCLE_NODE_INDEX=1
  - CIRCLE_NODE_TOTAL=8 CIRCLE_NODE_INDEX=2
  - CIRCLE_NODE_TOTAL=8 CIRCLE_NODE_INDEX=3
  - CIRCLE_NODE_TOTAL=8 CIRCLE_NODE_INDEX=4
  - CIRCLE_NODE_TOTAL=8 CIRCLE_NODE_INDEX=5
  - CIRCLE_NODE_TOTAL=8 CIRCLE_NODE_INDEX=6
  - CIRCLE_NODE_TOTAL=8 CIRCLE_NODE_INDEX=7
install:
  - "pip install ."
  - "pip install pytest"
  - "pip install git+https://github.com/pybee/pytest-circleci"
script:
  - "py.test tests"
