language: python
python:
  - "3.4.2"
  - "3.4.4"
env:
  - TEST_SUITE=tests.builtins
  - TEST_SUITE=tests.datatypes.test_bool
  - TEST_SUITE=tests.datatypes.test_bytearray
  - TEST_SUITE=tests.datatypes.test_bytes
  - TEST_SUITE=tests.datatypes.test_complex
  - TEST_SUITE=tests.datatypes.test_dict
  - TEST_SUITE=tests.datatypes.test_float
  - TEST_SUITE=tests.datatypes.test_frozenset
  - TEST_SUITE=tests.datatypes.test_int
  - TEST_SUITE=tests.datatypes.test_list
  - TEST_SUITE=tests.datatypes.test_NoneType
  - TEST_SUITE=tests.datatypes.test_NotImplemented
  - TEST_SUITE=tests.datatypes.test_range
  - TEST_SUITE=tests.datatypes.test_set
  - TEST_SUITE=tests.datatypes.test_slice
  - TEST_SUITE=tests.datatypes.test_str
  - TEST_SUITE=tests.datatypes.test_tuple
  - TEST_SUITE=tests.stdlib
  - TEST_SUITE=tests.structures
  - TEST_SUITE=tests.test_codecs
  - TEST_SUITE=tests.test_utils
install:
  - "pip install ."
  - "ant java"
script:
  - "python setup.py test -q -s $TEST_SUITE"
